main:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "Services"
    url: "/#services"
    weight: 2
    dropdown:
      - name: "Services"
        url: "/services/"

  - name: "Contact Us"
    url: "/#contact-us"
    weight: 3