main:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "Services"
    url: "/#services"
    weight: 2
    dropdown:
      - name: "Services"
        url: "/services/"

  - name: "Contact Us"
    url: "/#contact-us"
    weight: 3

dropdown:
  - name: "Aeration"
    url: "/services/aeration/"
    weight: 1

  - name: "Drainage Systems"
    url: "/services/drainage-systems/"
    weight: 2

  - name: "Grading"
    url: "/services/grading/"
    weight: 3

  - name: "Leveling"
    url: "/services/leveling/"
    weight: 4

  - name: "Overseeding"
    url: "/services/overseeding/"
    weight: 5

  - name: "Top Dressing"
    url: "/services/top-dressing/"
    weight: 6

#footer:
#  - name: "Home"
#    url: "/"
#    weight: 1
#
#  - name: "Contact Us"
#    url: "/contact-us"
#    weight: 4