title: "GreenLine Landscaping"
images: 
  - "images/hero-image.png"

logo: "images/logo-mini.png"

colors:
  primary: "#166534"
  secondary: "#22c55e"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  dribbble: "#"
  instagram: "https://www.instagram.com/localrootsweb?igsh=b2Z0bXE4dzJ0eWNh&utm_source=qr"
  facebook: "https://www.facebook.com/profile.php?id=61586705626333"
  twitter: "#"

locations:
  - "Cinco Ranch"
  - "Cypress"
  - "Katy"
  - "Sugar Land"

email:
  - "greenline@example.com"

phone:
  - "555.123.4567"

copyright: "© 2026 GreenLine Landscaping All Rights Reserved"

googleAnalytics: "G-XXXXXXXX"